// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZZUttgNFsiY7iJp9e_UiO1esJ_MIXkfM',
    appId: '1:439401271607:web:09d4a9ccce1d77a203cab2',
    messagingSenderId: '439401271607',
    projectId: 'portfolio-47193',
    authDomain: 'portfolio-47193.firebaseapp.com',
    storageBucket: 'portfolio-47193.firebasestorage.app',
    measurementId: 'G-TJ2R7NLPYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPncXJIEe3ijtN_CoMzQvtMwlMcgZNsEI',
    appId: '1:439401271607:android:eddd54555c5fa96503cab2',
    messagingSenderId: '439401271607',
    projectId: 'portfolio-47193',
    storageBucket: 'portfolio-47193.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpV8BgvCutg5iatO-a9zePTYspdLjFi0A',
    appId: '1:439401271607:ios:6a3f45434b024b7303cab2',
    messagingSenderId: '439401271607',
    projectId: 'portfolio-47193',
    storageBucket: 'portfolio-47193.firebasestorage.app',
    iosBundleId: 'com.example.portflio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpV8BgvCutg5iatO-a9zePTYspdLjFi0A',
    appId: '1:439401271607:ios:6a3f45434b024b7303cab2',
    messagingSenderId: '439401271607',
    projectId: 'portfolio-47193',
    storageBucket: 'portfolio-47193.firebasestorage.app',
    iosBundleId: 'com.example.portflio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZZUttgNFsiY7iJp9e_UiO1esJ_MIXkfM',
    appId: '1:439401271607:web:e123f82d60511fd303cab2',
    messagingSenderId: '439401271607',
    projectId: 'portfolio-47193',
    authDomain: 'portfolio-47193.firebaseapp.com',
    storageBucket: 'portfolio-47193.firebasestorage.app',
    measurementId: 'G-19KL56QJJ2',
  );
}
